# Run Inventory app
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventoryservice
  labels:
    app: inventoryservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventoryservice
  template:
    metadata:
      labels:
        app: inventoryservice
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: server
        image: inventoryservice
        ports:
        - name: http
          containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: REDIS_HOST
          value: "redis-cart"
        - name: REDIS_PORT
          value: "6379"

        startupProbe:
          tcpSocket:
            port: http
          periodSeconds: 5
          failureThreshold: 30
        readinessProbe:
          tcpSocket:
            port: http
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: http
          periodSeconds: 10
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}
---
# access via http://inventoryservice:8080 from Checkout
apiVersion: v1
kind: Service
metadata:
  name: inventoryservice
  labels:
    app: inventoryservice
spec:
  type: ClusterIP
  selector:
    app: inventoryservice
  ports:
  - name: http
    port: 8080
    targetPort: http
